db.products_services.update({ "_id" : ObjectId("5979b64adf098afe879d15ca")},{ 
    "_id" : ObjectId("5979b64adf098afe879d15ca"), 
    "org_id" : NumberInt(300001332), 
    "directoryName" : "OMD", 
    "directoryId" : ObjectId("57189b3e24d8bc65f4123bbf"), 
    "adsTypeId" : ObjectId("57baccd2c19cc75c73b7da9f"), 
    "adsTypeName" : "PREMIUM", 
    "name" : "Gyford Standoff Systems", 
    "companyName" : "Gyford Standoff Systems", 
    "companyLocalTitle" : "", 
    "sortName" : "", 
    "logoCaption" : "", 
    "companyListLogo" : "Gyford_Standoff_Systems.jpg", 
    "companyDetailsLogo" : "Gyford_Standoff_Systems.jpg", 
    "adsEditId" : NumberInt(0), 
    "userId" : NumberInt(300001332), 
    "cost" : 140.0, 
    "pay" : 0.0, 
    "laststep" : NumberInt(0), 
    "checked_out" : NumberInt(0), 
    "published" : NumberInt(1), 
    "changed" : NumberInt(0), 
    "approve_date" : null, 
    "hits" : NumberInt(2009), 
    "logoHits" : NumberInt(0), 
    "startDate" : ISODate("2010-01-23T00:08:20.000+0000"), 
    "endDate" : ISODate("2018-01-01T09:29:59.000+0000"), 
    "telephone" : "775-829-7272", 
    "companyFreePhone" : "", 
    "fax" : "775-201-7200", 
    "companyFreeFax" : "", 
    "companyEmail" : "info@standoffsystems.com", 
    "companyWebsite" : "www.standoffsystems.com", 
    "companyTypeHeader" : "Type of Business:", 
    "companyDescription" : "Gyford Standoff Systems has been designing and manufacturing decorative mounting hardware for the museum and display industry for over 20 years. Our StandOffs, rod and wire hanging systems are proudly made in the USA from environmentally sustainable, recycled aluminum and stainless steel. Gyford parts have been used in installations in The National History Museum of Los Angeles, the Art Institute of Chicago and the Smithsonian museums.<br><br> A team of Client Solution Specialist will assist in any design questions you have. Feel free to send them your drawing and they will work with you to ensure you get the hardware you need. Our website <a target='_blank' href='http://www.standoffsystems.com'>http://www.standoffsystems.com</a> includes product information, photo galleries, how-to videos and step-by-step guides.<br><br> We have over 2 million parts in stock, ready to ship within 24 hours and a full custom shop for your unique projects. Contact us today so we can help with your next museum installation.", 
    "metaDescription" : "", 
    "metaKeyword" : "Exhibit Cases, Exhibition Equipment & Services", 
    "companyAddress" : {
        "street1" : "891 Trademark Drive Reno, NV 89521", 
        "street2" : "", 
        "city" : null, 
        "stateId" : ObjectId("576230b9c19c494dcc08cefb"), 
        "state" : "NEVADA", 
        "stateAbbreviation" : "NV", 
        "country" : null, 
        "zip" : "89521", 
        "Telephone" : "775-829-7272", 
        "Fax" : "775-201-7200"
    }, 
    "location" : [
        -119.7511849, 
        39.4484502
    ], 
    "state" : ObjectId("57bc4b7dc19c0169d6e407f6"), 
    "categories" : [
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd93"), 
            "ProductCategoryName" : "Exhibits", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb25"), 
            "ProductSubCategoryName" : "Display Fixtures", 
            "ordering" : 0.0
        }, 
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd8d"), 
            "ProductCategoryName" : "Graphic Design/Publishing", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb3e"), 
            "ProductSubCategoryName" : "Exhibit Graphics", 
            "ordering" : 1.0
        }, 
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd93"), 
            "ProductCategoryName" : "Exhibits", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb2d"), 
            "ProductSubCategoryName" : "Hanging & Fastening Devices", 
            "ordering" : 0.0
        }
    ], 
    "personnel" : [
        {
            "personId" : 3.0133212E7, 
            "personnel_id" : NumberInt(5), 
            "adsId" : 3.00001332E8, 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "Michael", 
            "personLastName" : "Eddins", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "Sales Manager", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null
        }, 
        {
            "personId" : 3.0133205E7, 
            "personnel_id" : NumberInt(12), 
            "adsId" : 3.00001332E8, 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "Chris", 
            "personLastName" : "Howard", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "Marketing Coordinator", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null
        }
    ]
});