db.products_services.update({
  "_id" : ObjectId("57bc1275c19c7e32eadb0816")},{ 
    "_id" : ObjectId("57bc1275c19c7e32eadb0816"), 
    "org_id" : NumberInt(300006547), 
    "directoryName" : "OMD", 
    "directoryId" : ObjectId("57189b3e24d8bc65f4123bbf"), 
    "adsTypeId" : ObjectId("57baccd2c19cc75c73b7da9f"), 
    "adsTypeName" : "PREMIUM", 
    "name" : "ARTS CONSULTING GROUP", 
    "companyName" : "ARTS CONSULTING GROUP", 
    "companyLocalTitle" : "", 
    "sortName" : "", 
    "logoCaption" : "", 
    "companyListLogo" : "artsconsultinglogo_sm.jpg", 
    "companyDetailsLogo" : "artsconsultinglogo_lg.jpg", 
    "adsEditId" : NumberInt(300006547), 
    "userId" : NumberInt(0), 
    "cost" : 100.0, 
    "pay" : 0.0, 
    "laststep" : NumberInt(0), 
    "checked_out" : NumberInt(0), 
    "published" : NumberInt(1), 
    "changed" : NumberInt(0), 
    "approve_date" : null, 
    "hits" : NumberInt(0), 
    "logoHits" : NumberInt(0), 
    "startDate" : ISODate("2016-04-08T09:30:00.000+0000"), 
    "endDate" : ISODate("2019-01-30T09:30:00.000+0000"), 
    "telephone" : "888-234-4236", 
    "companyFreePhone" : "", 
    "fax" : "888-284-6651", 
    "companyFreeFax" : "", 
    "companyEmail" : "Museums@ArtsConsulting.com", 
    "companyWebsite" : "www.ArtsConsulting.com", 
    "companyTypeHeader" : "Type of Business:", 
    "companyDescription" : "<p style=\"text-align: justify;\">Arts Consulting Group is the leading provider of hands-on interim management, executive search, revenue enhancement consulting, facilities &amp; program planning, and organizational development services for the museum field. As a full service firm, ACG has a breadth and depth of experience with experienced consultants located throughout North America to best serve the needs of our clients.</p>\n", 
    "metaDescription" : "", 
    "metaKeyword" : "", 
    "companyAddress" : {
        "street1" : "292 Newbury Street, Suite 315", 
        "street2" : "", 
        "cityId" : ObjectId("57737614c19c5a58cc65684c"), 
        "city" : "Boston", 
        "stateId" : ObjectId("576230b9c19c494dcc08ceed"), 
        "stateAbbreviation" : "MA", 
        "state" : "MASSACHUSETTS", 
        "countryId" : ObjectId("5718d7abca75ca39db934831"), 
        "country" : "USA", 
        "zip" : "02115"
    }, 
    "location" : [
        -71.096848, 
        42.342043, 
        -96.115491, 
        33.104859
    ], 
    "state" : ObjectId("57bc4b7dc19c0169d6e407f6"), 
    "categories" : [
        {
            "_id" : ObjectId("5a3753c1a982a921905ac78b"), 
            "ordering" : NumberInt(0), 
            "ProductSubCategoryName" : "Fundraising/Membership Services", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeae3"), 
            "ProductCategoryName" : "Business/Retail Services", 
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd92")
        }, 
        {
            "_id" : ObjectId("5a3753c1a982a921905ac78a"), 
            "ordering" : NumberInt(0), 
            "ProductSubCategoryName" : "Executive Search Organizations", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb39"), 
            "ProductCategoryName" : "Museum Resources/Technical Information", 
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd8e")
        }, 
        {
            "_id" : ObjectId("5a3753c1a982a921905ac789"), 
            "ordering" : NumberInt(0), 
            "ProductSubCategoryName" : "Museum Planners", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb3b"), 
            "ProductCategoryName" : "Museum Resources/Technical Information", 
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd8e")
        }
    ], 
    "personnel" : [
        {
            "_id" : ObjectId("5a3753c1a982a921905ac788"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "President", 
            "PersonNameSuffix" : "", 
            "personLastName" : "Thibodeau", 
            "personName" : "Bruce D.", 
            "personPrefix" : "", 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300006547), 
            "personnel_id" : NumberInt(0), 
            "personId" : NumberInt(30654131)
        }, 
        {
            "_id" : ObjectId("5a3753c1a982a921905ac787"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Vice President - Museums", 
            "PersonNameSuffix" : "", 
            "personLastName" : "Harris", 
            "personName" : "Carolynne", 
            "personPrefix" : "", 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300006547), 
            "personnel_id" : NumberInt(0), 
            "personId" : NumberInt(30654133)
        }, 
        {
            "_id" : ObjectId("5a3753c1a982a921905ac786"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Vice President - Capital Campaign Planning", 
            "PersonNameSuffix" : "", 
            "personLastName" : "Galley", 
            "personName" : "Elisabeth", 
            "personPrefix" : "", 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300006547), 
            "personnel_id" : NumberInt(0), 
            "personId" : NumberInt(30654135)
        }, 
        {
            "_id" : ObjectId("5a3753c1a982a921905ac785"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Senior Vice President - ACG Canada", 
            "PersonNameSuffix" : "", 
            "personLastName" : "Bragg", 
            "personName" : "Martin", 
            "personPrefix" : "", 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300006547), 
            "personnel_id" : NumberInt(0), 
            "personId" : NumberInt(30654137)
        }
    ], 
    "stripName" : "ARTS CONSULTING GROUP", 
    "companyDescriptionSearch" : "Arts Consulting Group is the leading provider of hands on interim management executive search revenue enhancement consulting facilities program planning and organizational development services for the museum field As a full service firm ACG has a breadth and depth of experience with experienced consultants located throughout North America to best serve the needs of our clients"
});


db.products_services.update({"_id" : ObjectId("599e81b1beae40429249a9fd")},{ 
    "_id" : ObjectId("599e81b1beae40429249a9fd"), 
    "org_id" : 3.00006545E8, 
    "directoryName" : "OMD", 
    "directoryId" : ObjectId("57189b3e24d8bc65f4123bbf"), 
    "adsTypeId" : ObjectId("57baccd2c19cc75c73b7da9f"), 
    "adsTypeName" : "PREMIUM", 
    "name" : "ALL ACCESS EQUIPMENT", 
    "companyName" : "ALL ACCESS EQUIPMENT", 
    "companyLocalTitle" : "", 
    "sortName" : "", 
    "logoCaption" : "", 
    "companyListLogo" : "", 
    "companyDetailsLogo" : "", 
    "adsEditId" : 0.0, 
    "userId" : 0.0, 
    "cost" : 100.0, 
    "pay" : 0.0, 
    "laststep" : 0.0, 
    "checked_out" : 0.0, 
    "published" : 1.0, 
    "changed" : 0.0, 
    "approve_date" : null, 
    "hits" : 0.0, 
    "logoHits" : 0.0, 
    "startDate" : ISODate("2016-03-02T10:30:00.000+0000"), 
    "endDate" : ISODate("2019-01-30T09:30:00.000+0000"), 
    "telephone" : "978-712-4950", 
    "companyFreePhone" : "", 
    "fax" : "978-560-1256", 
    "companyFreeFax" : "", 
    "companyEmail" : "info@allaccessequipment.com", 
    "companyWebsite" : "allaccessequipment.com", 
    "companyTypeHeader" : "Type of Business:", 
    "companyDescription" : "<p style=\"text-align: justify;\">All Access Equipment provides simple solutions for difficult access. Our CMC tracked lifts offer compact dimensions and incredible reach in a very lightweight package. These lifts are safe, easy to operate, are fast and fun. They are the solution for difficult and previously impossible situations. CMC tracked lifts are articulating, track mounted, aerial lifts. We also offer our line of articulating loaders designed to fit in small places. Small packages, big reach.<br />\n<br />\nOur CMC tracked lifts are high quality aerial lifts which make work faster, safer, and less expensive compared to existing and potentially dangerous manual systems such as: ladders, scaffolding, ropes, saddles, and swing staging. This applies to both residential and commercial function.</p>\n", 
    "metaDescription" : "", 
    "metaKeyword" : "", 
    "companyAddress" : {
        "street1" : "891 Woburn Street", 
        "street2" : "", 
        "cityId" : ObjectId("576256d6264abc2b3b956826"), 
        "city" : "Wilmington", 
        "stateId" : ObjectId("576230b9c19c494dcc08ceed"), 
        "stateAbbreviation" : "MA", 
        "state" : "MASSACHUSETTS", 
        "countryId" : ObjectId("5718d7abca75ca39db934831"), 
        "country" : "USA", 
        "zip" : "01887"
    }, 
    "location" : [
        -95.757144, 
        39.094019
    ], 
    "state" : ObjectId("576230b9c19c494dcc08ceed"), 
    "categories" : [
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd8b"), 
            "ProductCategoryName" : "Building & Facilities", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb0f"), 
            "ProductSubCategoryName" : "Building & Facilities - General", 
            "ordering" : NumberInt(1), 
            "_id" : ObjectId("5a3753fba982a921905ac790")
        }, 
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd8b"), 
            "ProductCategoryName" : "Building & Facilities", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb5c"), 
            "ProductSubCategoryName" : "Maintenance & Equipment", 
            "ordering" : NumberInt(1), 
            "_id" : ObjectId("5a3753fba982a921905ac78f")
        }, 
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd8b"), 
            "ProductCategoryName" : "Building & Facilities", 
            "ProductSubCategory" : ObjectId("599e66170c778d26754cbd47"), 
            "ProductSubCategoryName" : "Maintenance & Equip. for Buildings", 
            "ordering" : NumberInt(1), 
            "_id" : ObjectId("5a3753fba982a921905ac78e")
        }
    ], 
    "personnel" : [
        {
            "personId" : NumberInt(30654117), 
            "personnel_id" : NumberInt(0), 
            "adsId" : NumberInt(300006545), 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "Ryan", 
            "personLastName" : "Polonski", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null, 
            "_id" : ObjectId("5a3753fba982a921905ac78d")
        }, 
        {
            "personId" : NumberInt(30654117), 
            "personnel_id" : NumberInt(0), 
            "adsId" : NumberInt(300006545), 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "Lenny", 
            "personLastName" : "Polonski", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null, 
            "_id" : ObjectId("5a3753fba982a921905ac78c")
        }
    ], 
    "stripName" : "ALL ACCESS EQUIPMENT", 
    "companyDescriptionSearch" : "All Access Equipment provides simple solutions for difficult access Our CMC tracked lifts offer compact dimensions and incredible reach in a very lightweight package These lifts are safe easy to operate are fast and fun They are the solution for difficult and previously impossible situations CMC tracked lifts are articulating track mounted aerial lifts We also offer our line of articulating loaders designed to fit in small places Small packages big reach Our CMC tracked lifts are high quality aerial lifts which make work faster safer and less expensive compared to existing and potentially dangerous manual systems such as ladders scaffolding ropes saddles and swing staging This applies to both residential and commercial function"
});