db.products_services.update({ "_id": ObjectId("57bd8f03c19c1584dd31b82c") }, {
    "_id": ObjectId("57bd8f03c19c1584dd31b82c"),
    "org_id": NumberInt(300006637),
    "directoryName": "OCD",
    "directoryId": ObjectId("57189cd924d8bc65f4123bc3"),
    "adsTypeId": ObjectId("57baccd2c19cc75c73b7da9f"),
    "adsTypeName": "PREMIUM",
    "name": "The Christophers",
    "companyName": "The Christophers",
    "companyLocalTitle": "",
    "sortName": "",
    "logoCaption": "",
    "companyListLogo": "christopherlogo_sm.jpg",
    "companyDetailsLogo": "christopherslogo_lg.jpg",
    "adsEditId": NumberInt(0),
    "userId": NumberInt(0),
    "cost": 80.0,
    "pay": 0.0,
    "laststep": NumberInt(0),
    "checked_out": NumberInt(0),
    "published": NumberInt(1),
    "changed": NumberInt(0),
    "approve_date": null,
    "hits": NumberInt(0),
    "logoHits": NumberInt(0),
    "startDate": ISODate("2012-05-24T09:30:00.000+0000"),
    "endDate": ISODate("2018-12-31T09:30:00.000+0000"),
    "telephone": "888-298-4050; 212-759-4050",
    "companyFreePhone": "",
    "fax": "212-838-5073",
    "companyFreeFax": "",
    "companyEmail": "mail@christophers.org",
    "companyWebsite": "www.christophers.org",
    "companyTypeHeader": "Type of Business:",
    "companyDescription": "<p>A non-profit founded in 1945 by Father James Keller, M.M., and grounded in Judeo-Christian principles, The Christophers encourage people to use their God-given talents to make a positive difference in the world. By sharing their gifts with others, each person becomes a Christ-bearer, a &ldquo;Christopher&rdquo; in the most fundamental sense of that word. The mission is best expressed in The Christophers&rsquo; motto: &ldquo;It&rsquo;s better to light one candle than to curse the darkness.&rdquo;&nbsp;<br /> \nThe Christophers&rsquo; outreach includes: <strong>Christopher News Notes,</strong> motivational pamphlets; <strong><em>Christopher Closeup</em></strong>, radio show/podcast and blog; <strong>Christopher Awards</strong> for TV, Films, and Books; <strong>Christopher Leadership Courses;</strong> <em><strong>Three Minutes a Day</strong></em> books; <strong>Annual Poster Contest for High School Students; Annual Video Contest for College Students; Christopher Minutes,</strong> syndicated radio PSAs; <em><strong>Light One Candle,</strong></em> columns; <strong>Honor and Memorial Cards; Military and Prison ministries; Donations of Christopher materials</strong> to the needy; <strong>Online ministry,</strong> etc.</p>",
    "metaKeyword": "Professional Associations & Organizations—General \r\n Spiritual Enrichment",
    "metaDescription": "",
    "companyAddress": {
        "street1": "5 Hanover Square, 22nd Floor",
        "street2": "",
        "cityId": ObjectId("576256fe264abc2b3b957b93"),
        "city": "New York",
        "stateId": ObjectId("576230b9c19c494dcc08cefc"),
        "stateAbbreviation": "NY",
        "state": "NEW YORK",
        "countryId": ObjectId("5718d7abca75ca39db934831"),
        "country": "USA",
        "zip": "10004"
    },
    "state": ObjectId("57bc4b7dc19c0169d6e407f6"),
    "location": [-74.025276,
        40.696355
    ],
    "categories": [{
            "_id": ObjectId("5a0bec01649497896ce13787"),
            "ordering": NumberInt(0),
            "ProductSubCategoryName": "Spiritual Enrichment",
            "ProductSubCategory": ObjectId("57bd7019c19c282e99fd878f"),
            "ProductCategoryName": "Education",
            "ProductCategory": ObjectId("57bd4e14c19c2d37eb85de28")
        },
        {
            "_id": ObjectId("5a0bec01649497896ce13786"),
            "ordering": NumberInt(0),
            "ProductSubCategoryName": "Professional Associations & Organizations—General",
            "ProductSubCategory": ObjectId("57bd7019c19c282e99fd8782"),
            "ProductCategoryName": "Professional Associations & Organizations",
            "ProductCategory": ObjectId("57bd4e14c19c2d37eb85de2b")
        }
    ],
    "personnel": [{
            "_id": ObjectId("5a0bec01649497896ce13785"),
            "personFax": null,
            "personPhone": null,
            "personEmail": null,
            "personDesignation": "President",
            "PersonNameSuffix": "",
            "personLastName": "Okulski",
            "personName": "Robert V.",
            "personPrefix": "",
            "responseCodeName": null,
            "responseCode": null,
            "adsId": NumberInt(0),
            "personnel_id": NumberInt(0),
            "personId": NumberInt(30653687)
        },
        {
            "_id": ObjectId("5a0bec01649497896ce13784"),
            "personFax": null,
            "personPhone": null,
            "personEmail": null,
            "personDesignation": "Vice President/COO",
            "PersonNameSuffix": "",
            "personLastName": "Robinson",
            "personName": "Mary Ellen",
            "personPrefix": "",
            "responseCodeName": null,
            "responseCode": null,
            "adsId": NumberInt(0),
            "personnel_id": NumberInt(0),
            "personId": NumberInt(30653689)
        },
        {
            "_id": ObjectId("5a0bec01649497896ce13783"),
            "personFax": null,
            "personPhone": null,
            "personEmail": null,
            "personDesignation": "Director of Communications",
            "PersonNameSuffix": "",
            "personLastName": "Rossi",
            "personName": "Tony",
            "personPrefix": "",
            "responseCodeName": null,
            "responseCode": null,
            "adsId": NumberInt(0),
            "personnel_id": NumberInt(0),
            "personId": NumberInt(30653691)
        },
        {
            "_id": ObjectId("5a0bec01649497896ce13782"),
            "personFax": null,
            "personPhone": null,
            "personEmail": null,
            "personDesignation": "Finance Manager",
            "PersonNameSuffix": "",
            "personLastName": "Santos",
            "personName": "Yaneza",
            "personPrefix": "",
            "responseCodeName": null,
            "responseCode": null,
            "adsId": NumberInt(0),
            "personnel_id": NumberInt(0),
            "personId": NumberInt(30653693)
        }
    ]
})