db.products_services.update({"_id" : ObjectId("57bc1276c19c7e32eadb08a3")},{ 
    "_id" : ObjectId("57bc1276c19c7e32eadb08a3"), 
    "org_id" : NumberInt(300001754), 
    "directoryName" : "OMD", 
    "directoryId" : ObjectId("57189b3e24d8bc65f4123bbf"), 
    "adsTypeId" : ObjectId("57baccd2c19cc75c73b7da9f"), 
    "adsTypeName" : "PREMIUM", 
    "name" : "HUNTINGTON T BLOCK INSURANCE AGENCY INC AN AON GROUP COMPANY", 
    "companyName" : "HUNTINGTON T. BLOCK INSURANCE AGENCY, INC. AN AON GROUP COMPANY", 
    "companyLocalTitle" : "", 
    "sortName" : "", 
    "logoCaption" : "", 
    "companyListLogo" : "Huntington.logo.jpg", 
    "companyDetailsLogo" : "Huntington.logo.jpg", 
    "adsEditId" : NumberInt(0), 
    "userId" : NumberInt(300001754), 
    "cost" : 60.0, 
    "pay" : 0.0, 
    "laststep" : NumberInt(0), 
    "checked_out" : NumberInt(0), 
    "published" : NumberInt(1), 
    "changed" : NumberInt(0), 
    "approve_date" : null, 
    "hits" : NumberInt(990), 
    "logoHits" : NumberInt(0), 
    "startDate" : ISODate("2012-05-24T09:30:00.000+0000"), 
    "endDate" : ISODate("2018-12-31T09:30:00.000+0000"), 
    "telephone" : "855-219-3189(DC) & 866-692-4565 (NY)", 
    "companyFreePhone" : "800-424-8830", 
    "fax" : "202-331-8409", 
    "companyFreeFax" : "", 
    "companyEmail" : "Jeff.Minett@aon.com", 
    "companyWebsite" : "www.huntingtontblock.com", 
    "companyTypeHeader" : "Type of Business:", 
    "companyDescription" : "<p style=\"text-align: justify;\">HTB is a leading provider of insurance services for museums &amp; exhibitions, universities, galleries, collectors, artists &amp; conservators. As a full service brokerage firm, we offer one-stop-shopping for business insurance designed with museums in mind, in addition to an in-house Fine Art insurance claims department, proprietary museum collection and temporary loans policy forms and $600M in exclusive aggregate limit capacity via our Lloyd’s of London underwriting facilities. Office locations include Washington DC, New York City, Houston and representation in San Francisco and London.</p>\n", 
    "metaDescription" : "", 
    "metaKeyword" : "insurance", 
    "companyAddress" : {
        "street1" : "1120 20th St., N.W., Suite 600", 
        "street2" : "", 
        "cityId" : ObjectId("577df51cc19c29cdc2772d62"), 
        "city" : "Washington", 
        "stateId" : ObjectId("576230b9c19c494dcc08cee1"), 
        "stateAbbreviation" : "DC", 
        "state" : "DISTRICT OF COLUMBIA", 
        "countryId" : ObjectId("5718d7abca75ca39db934831"), 
        "country" : "USA", 
        "zip" : "20036-3406"
    }, 
    "location" : [
        -77.039914, 
        38.900659
    ], 
    "state" : ObjectId("57bc4b7dc19c0169d6e407f6"), 
    "categories" : [
        {
            "_id" : ObjectId("59f06b0ae87400237884ca71"), 
            "ordering" : NumberInt(0), 
            "ProductSubCategoryName" : "Insurance", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb0c"), 
            "ProductCategoryName" : "Business/Retail Services", 
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd92")
        }
    ], 
    "personnel" : [
        {
            "_id" : ObjectId("59f06b0ae87400237884ca70"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "San Francisco, Fine Art Insurance", 
            "PersonNameSuffix" : null, 
            "personLastName" : "Barr", 
            "personName" : "Sarah", 
            "personPrefix" : null, 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300001754), 
            "personnel_id" : NumberInt(11), 
            "personId" : NumberInt(30175411)
        }, 
        {
            "_id" : ObjectId("59f06b0ae87400237884ca6f"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Houston, Fine Art Insurance", 
            "PersonNameSuffix" : null, 
            "personLastName" : "Reid", 
            "personName" : "Adrienne", 
            "personPrefix" : null, 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300001754), 
            "personnel_id" : NumberInt(10), 
            "personId" : NumberInt(30175410)
        }, 
        {
            "_id" : ObjectId("59f06b0ae87400237884ca6e"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Washington DC, Commercial Lines Insurance", 
            "PersonNameSuffix" : null, 
            "personLastName" : "Mercado", 
            "personName" : "Richard", 
            "personPrefix" : null, 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300001754), 
            "personnel_id" : NumberInt(12), 
            "personId" : NumberInt(30175412)
        }, 
        {
            "_id" : ObjectId("59f06b0ae87400237884ca6d"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Washington DC, Fine Art Insurance", 
            "PersonNameSuffix" : null, 
            "personLastName" : "Minett", 
            "personName" : "Jeff", 
            "personPrefix" : null, 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300001754), 
            "personnel_id" : NumberInt(3), 
            "personId" : NumberInt(30175403)
        }, 
        {
            "_id" : ObjectId("59f06b0ae87400237884ca6c"), 
            "personFax" : null, 
            "personPhone" : null, 
            "personEmail" : null, 
            "personDesignation" : "Baltimore MD, Fine Art Insurance", 
            "PersonNameSuffix" : "", 
            "personLastName" : "Marcin", 
            "personName" : "Lynn", 
            "personPrefix" : "", 
            "responseCodeName" : null, 
            "responseCode" : null, 
            "adsId" : NumberInt(300001754), 
            "personnel_id" : NumberInt(9), 
            "personId" : NumberInt(30175409)
        }
    ], 
    "stripName" : "HUNTINGTON T  BLOCK INSURANCE AGENCY  INC  AN AON GROUP COMPANY", 
    "companyDescriptionSearch" : "HTB is a leading provider of insurance services for museums amp exhibitions universities galleries collectors artists amp conservators As a full service brokerage firm we offer one stop shopping for business insurance designed with museums in mind in addition to an in house Fine Art insurance claims department proprietary museum collection and temporary loans policy forms and 600M in exclusive aggregate limit capacity via our Lloyd s of London underwriting facilities Office locations include Washington DC New York City Houston and representation in San Francisco and London"
});

db.products_services.update({"_id" : ObjectId("57bc1276c19c7e32eadb085f")},
{ 
    "_id" : ObjectId("57bc1276c19c7e32eadb085f"), 
    "org_id" : NumberInt(300000398), 
    "directoryName" : "OMD", 
    "directoryId" : ObjectId("57189b3e24d8bc65f4123bbf"), 
    "adsTypeId" : ObjectId("57baccd2c19cc75c73b7da9f"), 
    "adsTypeName" : "PREMIUM", 
    "name" : "JRA JACK ROUSE ASSOCIATES", 
    "companyName" : "JRA (JACK ROUSE ASSOCIATES)", 
    "companyLocalTitle" : "", 
    "sortName" : "", 
    "logoCaption" : "", 
    "companyListLogo" : "jackrouselogo_sm.jpg", 
    "companyDetailsLogo" : "JackRouseLogo18.jpg", 
    "adsEditId" : NumberInt(0), 
    "userId" : NumberInt(300000398), 
    "cost" : 60.0, 
    "pay" : 0.0, 
    "laststep" : NumberInt(0), 
    "checked_out" : NumberInt(0), 
    "published" : NumberInt(1), 
    "changed" : NumberInt(0), 
    "approve_date" : null, 
    "hits" : NumberInt(4620), 
    "logoHits" : NumberInt(0), 
    "startDate" : ISODate("2012-05-24T09:30:00.000+0000"), 
    "endDate" : ISODate("2018-12-31T09:30:00.000+0000"), 
    "telephone" : "513-381-0055", 
    "companyFreePhone" : "", 
    "fax" : "513-381-2691", 
    "companyFreeFax" : "", 
    "companyEmail" : "smccoy@jackrouse.com", 
    "companyWebsite" : "www.jackrouse.com/museum/index.cfm", 
    "companyTypeHeader" : "Type of Business:", 
    "companyDescription" : "<p style=\"text-align: justify;\">At JRA, we understand that a museum’s mission, first and foremost, is to educate. We also understand that learning can be fun. Using strong story lines, immersive environments and interactives, we plan, design, and realize exhibits that attract visitors to cultural institutions and engage them in the joy of learning. Within our full-time staff are content developers, writers, planners, designers, media producers, and project managers representing many disciplines. Because of our reputation for innovation, we have been fortunate to work with some of the world’s most respected organizations, helping them create memorable experiences that truly connect with people.</p>\n", 
    "metaDescription" : "", 
    "metaKeyword" : "", 
    "companyAddress" : {
        "street1" : "600 Vine St., Ste. 1700", 
        "street2" : "", 
        "cityId" : ObjectId("57728a9ec19ce86ca8a14e57"), 
        "city" : "Cincinnati", 
        "stateId" : ObjectId("576230b9c19c494dcc08cefd"), 
        "stateAbbreviation" : "OH", 
        "state" : "OHIO", 
        "countryId" : ObjectId("5718d7abca75ca39db934831"), 
        "country" : "USA", 
        "zip" : "45202-1100"
    }, 
    "location" : [
        -84.486142, 
        39.11026
    ], 
    "state" : ObjectId("57bc4b7dc19c0169d6e407f6"), 
    "categories" : [
        {
            "ProductCategory" : ObjectId("57b6ee10c19cc2c7e675cd93"), 
            "ProductCategoryName" : "Exhibits", 
            "ProductSubCategory" : ObjectId("57b6f47cc19cf1479fffeb1c"), 
            "ProductSubCategoryName" : "Exhibit Design Firms", 
            "ordering" : NumberInt(0), 
            "_id" : ObjectId("59f06ba1e87400237884ca73")
        }
    ], 
    "personnel" : [
        {
            "personId" : NumberInt(30039811), 
            "personnel_id" : NumberInt(11), 
            "adsId" : NumberInt(300000398), 
            "responseCode" : ObjectId("5763caeec19c69bbc4bd3f7b"), 
            "responseCodeName" : "Marketing/Public Relations/Affairs", 
            "personPrefix" : null, 
            "personName" : "Shawn", 
            "personLastName" : "McCoy", 
            "PersonNameSuffix" : null, 
            "personDesignation" : "Vice President", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null, 
            "_id" : ObjectId("59f06ba1e87400237884ca72")
        }
    ], 
    "stripName" : "JRA  JACK ROUSE ASSOCIATES ", 
    "companyDescriptionSearch" : "At JRA we understand that a museum s mission first and foremost is to educate We also understand that learning can be fun Using strong story lines immersive environments and interactives we plan design and realize exhibits that attract visitors to cultural institutions and engage them in the joy of learning Within our full time staff are content developers writers planners designers media producers and project managers representing many disciplines Because of our reputation for innovation we have been fortunate to work with some of the world s most respected organizations helping them create memorable experiences that truly connect with people"
});

db.products_services.update({"_id" : ObjectId("5a0d5f8da229d3b67a9b9aa0")},{ 
    "_id" : ObjectId("5a0d5f8da229d3b67a9b9aa0"), 
    "org_id" : NumberInt(300006574), 
    "directoryName" : "OCD", 
    "directoryId" : ObjectId("57189cd924d8bc65f4123bc3"), 
    "adsTypeId" : ObjectId("57baccd2c19cc75c73b7da9f"), 
    "adsTypeName" : "PREMIUM", 
    "name" : "GP Catholic Services", 
    "companyName" : "GP Catholic Services", 
    "companyLocalTitle" : "", 
    "sortName" : "", 
    "logoCaption" : "", 
    "companyListLogo" : "GPCatholicLogo18.jpg", 
    "companyDetailsLogo" : "GPCatholicLogo18.jpg", 
    "adsEditId" : NumberInt(0), 
    "userId" : NumberInt(0), 
    "cost" : 60.0, 
    "pay" : 0.0, 
    "laststep" : NumberInt(0), 
    "checked_out" : NumberInt(0), 
    "published" : NumberInt(1), 
    "changed" : NumberInt(0), 
    "approve_date" : null, 
    "hits" : NumberInt(0), 
    "logoHits" : NumberInt(0), 
    "startDate" : ISODate("2012-05-24T09:30:00.000+0000"), 
    "endDate" : ISODate("2018-12-31T09:30:00.000+0000"), 
    "telephone" : "202-756-2240", 
    "companyFreePhone" : "", 
    "fax" : "", 
    "companyFreeFax" : "", 
    "companyEmail" : "welcome@gpcatholic.com", 
    "companyWebsite" : "www.gpcatholic.com", 
    "companyTypeHeader" : "Type of Business:", 
    "companyDescription" : "<p style=\"text-align: justify;\">GP Catholic Services is a leading fundraising consulting firm serving the Catholic Church. We specialize in designing and managing fundraising campaigns for dioceses, parishes, religious orders and congregations. GP Catholic Services is a division of Graham-Pelton Consulting. We offer decades of fundraising and development experience with a powerful focus on the Catholic Church.</p>\n", 
    "metaDescription" : "", 
    "metaKeyword" : "Bibles, Hymnals, Missalettes", 
    "companyAddress" : {
        "street1" : "Worldwide", 
        "street2" : "", 
        "city" : "", 
        "stateAbbreviation" : "PA", 
        "state" : "", 
        "country" : "", 
        "zip" : ""
    }, 
    "state" : ObjectId("57bc4b7dc19c0169d6e407f6"), 
    "location" : [
        -75.150071, 
        39.950004
    ], 
    "categories" : [
        {
            "_id" : ObjectId("59f17b759b7e524229624bec"), 
            "ProductCategory" : ObjectId("57bd4e14c19c2d37eb85de24"), 
            "ProductCategoryName" : "Fundraising", 
            "ProductSubCategory" : ObjectId("57bd7019c19c282e99fd878d"), 
            "ProductSubCategoryName" : "Fundraising Counseling"
        }, 
        {
            "_id" : ObjectId("59f17b759b7e524229624be9"), 
            "ProductCategory" : ObjectId("57bd4e14c19c2d37eb85de24"), 
            "ProductCategoryName" : "Fundraising", 
            "ProductSubCategory" : ObjectId("57bd7019c19c282e99fd877f"), 
            "ProductSubCategoryName" : "Fundraising Services"
        }
    ], 
    "personnel" : [
        {
            "personId" : NumberInt(30653491), 
            "personnel_id" : NumberInt(1), 
            "adsId" : NumberInt(0), 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "William", 
            "personLastName" : "Gorman", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "Managing Director", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null, 
            "_id" : ObjectId("59f716d128d857039c62dcdd")
        }, 
        {
            "personId" : NumberInt(30653491), 
            "personnel_id" : NumberInt(2), 
            "adsId" : NumberInt(0), 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "Dan", 
            "personLastName" : "Conway", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "Strategic Planning + Development + Pastoral Leadership", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null, 
            "_id" : ObjectId("59f716d128d857039c62dcdd")
        }, 
        {
            "personId" : NumberInt(30653491), 
            "personnel_id" : NumberInt(4), 
            "adsId" : NumberInt(0), 
            "responseCode" : null, 
            "responseCodeName" : null, 
            "personPrefix" : "", 
            "personName" : "Nicole", 
            "personLastName" : "Antil", 
            "PersonNameSuffix" : "", 
            "personDesignation" : "Creative Strategy + Design Leadership + Process Development", 
            "personEmail" : null, 
            "personPhone" : null, 
            "personFax" : null, 
            "_id" : ObjectId("59f716d128d857039c62dcdd")
        }
    ], 
    "stripName" : "GP Catholic Services", 
    "companyDescriptionSearch" : "GP Catholic Services is a leading fundraising consulting firm serving the Catholic Church We specialize in designing and managing fundraising campaigns for dioceses parishes religious orders and congregations GP Catholic Services is a division of Graham Pelton Consulting We offer decades of fundraising and development experience with a powerful focus on the Catholic Church"
});
